# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-render"
BBFILE_PATTERN_meta-render = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-render = "6"

LAYERDEPENDS_meta-render = "core"
LAYERSERIES_COMPAT_meta-render = "scarthgap"
